[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Olie Chan <olie.chan@infinityworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.8"
