[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Olie Chan <olie.chan.141@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path="src/lib.rs"

[[bin]]
path="src/main.rs"
name="zero2prod"

[dependencies]
actix-web = "4.0.0-beta.8"
# We need the optional`derive`feature to use`serde`'s procedural macros:#`#[derive(Serialize)]`and`#[derive(Deserialize)]`.# The feature is not enabled by default to avoid pulling in# unnecessary dependencies for projects that do not need it.
serde = { version = "1", features = ["derive"]}

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
